[package]

name = "demo"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies]
gdi32-sys = "*"
kernel32-sys = "*"
user32-sys = "*"
winapi = "*"

[dependencies.mantle-sys]
path = "../mantle-sys"
